# Generated by Django 2.2.7 on 2019-12-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0003_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.IntegerField()),
                ('followed_id', models.IntegerField()),
            ],
        ),
    ]
