# Generated by Django 2.2.7 on 2020-01-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0006_auto_20191220_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(default='You have not set your About Me', max_length=500),
        ),
    ]
