# Generated by Django 2.2.7 on 2020-01-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0008_remove_user_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(default='You have not set your About Me', max_length=500),
        ),
    ]
